# Generated by Django 3.2.2 on 2021-05-11 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0002_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.ManyToManyField(to='filmy.Genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='screen_play',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='written_by', to='filmy.person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directed_by', to='filmy.person'),
        ),
    ]
