# Generated by Django 3.2.2 on 2021-05-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0004_auto_20210511_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
